### PR TITLE
Add magicc adapter

### PR DESCRIPTION
**Pull request by znicholls**
# Pull request

Please confirm that this pull request has done the following:

- [ ] Included way of handling models as dependencies, as discussed in #2 
- [ ] Made decision about how to include rcp data
- [ ] Tests added
- [ ] Documentation added (where applicable)
- [ ] Example added (either to an existing notebook or as a new notebook, where applicable)
- [ ] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <http://link-to-pr.com>`_) Added feature which does something
- (`#XX <http://link-to-pr.com>`_) Fixed bug identified in (`#XX <http://link-to-issue.com>`_)
```

Adds an adapter for MAGICC

### CODE REVIEW

**Comment by swillner** [comment]
Nice! I guess it’s time we write a “How to implement an adapter”-section. In #41 I changed some of the stucture already, so I think we should have a call regarding adapter implementation very soon. What about beginning of next week, @znicholls ?

**Comment by znicholls** [comment]
> What about beginning of next week, @znicholls ?

Fine for me (Monday better than Tuesday, we also have OpenSCM call Wednesday).

**Comment by znicholls** [comment]
> “How to implement an adapter”-section

I agree, although I'd be more inclined to follow the pandas extensionarray style where the adapters must pass a series of pre-defined tests before being approved.

**Comment by swillner** [comment]
>> What about beginning of next week, @znicholls ? ...

@znicholls @rgieseke Monday at 10am (ger) / 8pm (aus)?

**Comment by swillner** [comment]
@znicholls Sorry to ask again: How does this PR differ from #88 ?

**Comment by znicholls** [comment]
> How does this PR differ from #88 ?

Not tested as well and I don't intend to ever merge this, it's just a sandbox where I've tried things and from which I'll create smaller PRs to go into master.

**Pull request closed without merging**
