### PR TITLE
Add resample method for ScmDataFrame

### PR DESCRIPTION
**Pull request by lewisjared**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [x] Documentation added (where applicable)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/openclimatedata/openscm/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/openclimatedata/openscm/pull/XX>`_) Fixed bug identified in `#YY <https://github.com/openclimatedata/openscm/issues/YY>`_
```

### CODE REVIEW

**Comment by lewisjared** [comment]
Note this currently uses master from xarray

**Comment by znicholls** [comment]
> This looks like it should actually use the low-level api for consistency... What does it do differently and why is it necessary for the high-level api?

It's a sprint solution which we need for this week. Happy to discuss more when we propose merging anything into master.

**Comment by swillner** [comment]
hmm, shound we have a separate branch for your urgent stuff instead of including in master and then reverting later?

**Comment by znicholls** [comment]
> sorry, I should really look at what's the target branch ;)

do you want us to use a label for stuff that's not going into master?

**Comment by swillner** [comment]
>> sorry, I should really look at what's the target branch ;) ...

@znicholls would be great! or use a fork for these sprints. are you going to have more like these in the coming weeks?

**Comment by znicholls** [comment]
> or use a fork for these sprints

I thought about that, seemed antisocial but would happily switch if you prefer...

> are you going to have more like these in the coming weeks?

No I anticipate this is the only one.

**Comment by swillner** [comment]
>> or use a fork for these sprints ...

@znicholls then just keep going as you have and I'll look at the target branch properly ;) next time let's just communicate that to the whole team. we could also just accept PRs from private forks as feature branches and use branches in the openscm repo only for big stuff...

**Comment by lewisjared** [comment]
> This looks like it should actually use the low-level api for consistency... What does it do differently and why is it necessary for the high-level api?

@swillner  What do you mean by this? The hackery is to handle use cases where time series span longer than 292 years - pandas.resample doesn't handle that at all.

**Comment by swillner** [comment]
> > This looks like it should actually use the low-level api for consistency... What does it do differently and why is it necessary for the high-level api?
> 
> @swillner What do you mean by this? The hackery is to handle use cases where time series span longer than 292 years - pandas.resample doesn't handle that at all.

As I (maybe wrongly) understand the purpose of this feature is to change the resolution of a time series (aka time frames as we called in the docs). We have something like that already in the "low-level API" (shoul really change that name) with the ``TimeframeConverter`` class. But maybe I just misunderstood what you are doing in this PR.

**Comment by znicholls** [comment]
> As I (maybe wrongly) understand the purpose of this feature is to change the resolution of a time series (aka time frames as we called in the docs). We have something like that already in the "low-level API" (shoul really change that name) with the `TimeframeConverter` class. But maybe I just misunderstood what you are doing in this PR.

I think we're all agreeing here. We should have one way to do this, and it probably should be via the low-level API in the end, but we just haven't got to it yet. Let's revisit when we come to a merge into master.

**Pull request merged**
