### PR TITLE
Model overview

### PR DESCRIPTION
**Pull request by rgieseke**
# Pull request

Please confirm that this pull request has done the following:

- [ ] Tests added
- [ ] Documentation added (where applicable)
- [ ] Example added (either to an existing notebook or as a new notebook, where applicable)
- [ ] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <http://link-to-pr.com>`_) Added feature which does something
- (`#XX <http://link-to-pr.com>`_) Fixed bug identified in (`#XX <http://link-to-issue.com>`_)
```

### CODE REVIEW

**Comment by rgieseke** [comment]
In #13 @swillner started an overview which might be more useful for an overview than separate pages -- however it could be nice to generate such a table programmatically.

**Comment by rgieseke** [comment]
> How would we build that programmatically? Add something like __description__ to each model adapter?

Also nice, i had thought of having a YAML file or something and generate tables from that.

**Comment by swillner** [comment]
Do we still need this PR? What do we include in #104?

**Comment by swillner** [comment]
Will incorprate in #104

**Pull request closed without merging**
