### PR TITLE
Add magicc backend

### PR DESCRIPTION
**Pull request by znicholls**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [x] Documentation added (where applicable)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <http://link-to-pr.com>`_) Added feature which does something
- (`#XX <http://link-to-pr.com>`_) Fixed bug identified in (`#XX <http://link-to-issue.com>`_)
```

### CODE REVIEW

**Comment by znicholls** [comment]
@lewisjared this now has the failing append test included

**Comment by znicholls** [comment]
@lewisjared this is good to go tomorrow (tests are failing as CI doesn't have wine I believe)

**Comment by lewisjared** [comment]
This is a big read. Can you spend a few moments and run me through it as I don't know much about how the Adapters/ParameterSet functionality works?

Perhaps you mock the call to `pymagicc.run`

**Comment by znicholls** [comment]
Huge read, let's spend 10 minutes this morning

**Pull request merged**
