### PR TITLE
Add ph99 model scmcallib

### PR DESCRIPTION
**Pull request by znicholls**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [x] Documentation added (where applicable)
- [ ] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/openclimatedata/openscm/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/openclimatedata/openscm/pull/XX>`_) Fixed bug identified in `#YY <https://github.com/openclimatedata/openscm/issues/YY>`_
```

@lewisjared this just adds the PH99 model, not the adapter yet

### CODE REVIEW

**Comment by swillner** [comment]
What is the difference to #60? And why "scmcallib"?

**Comment by znicholls** [comment]
> What is the difference to #60?

Slightly better isolated.

> And why "scmcallib"?

It's to go into the `scmcallib` branch i.e. Jared and my mad sprint to try and get things working by Monday

**Comment by swillner** [comment]
oh, I would have had some remarks...

**Comment by znicholls** [comment]
> oh, I would have had some remarks

Whilst we're in this mad period you're welcome to jump in but it's going to be messy and sometimes not always involve proper consultation. We would never do this for PRs into master, but there's a different goal here. All of the functionality will eventually come into master, just in a much better form as it'll be based off much more thorough discussions about how we do things rather than 'anything that seems to half work'.

**Comment by swillner** [comment]
ah, sorry, I thought it was going into master ;) my bad

**Pull request merged**
