### PR TITLE
Re-add build and coverage badges, closes #130

### LINKED ISSUE #130: Badges
Can we get code coverage and build state badges back? They've always been a big source of confidence for me.

### PR DESCRIPTION
**Pull request by swillner**

### CODE REVIEW

**Comment by znicholls** [comment]
Ok so we just hard code passing and 100% as we know that's the case?

**Comment by swillner** [comment]
Yes, otherwise we could only have a dynamic badge with red/yellow/green for the github actions. But we ensure passing build and coverage on the master branch, anyway. Once we have a release at least the build badge will be redundant, probably.

**Comment by znicholls** [comment]
Hmm ok how about we scrap the build/coverage badges and just add a badge which links to the actions page?

**Comment by swillner** [comment]
Would be from here: https://github.com/CultureHQ/github-actions-badge
ok?

**Comment by znicholls** [comment]
> ok?

Perfect :)

**Pull request merged**
