### PR TITLE
Fix type annotations and enforce them in Github Actions

### PR DESCRIPTION
**Pull request by swillner**
Use [Mypy](https://mypy.readthedocs.io/) to enforce typing.

### CODE REVIEW

**Comment by znicholls** [comment]
@swillner is it possible to split the typing stuff from the timeseries stuff please? Do the type annotations only apply if they're there, or will this force to provide type annotations for everything?

**Comment by swillner** [comment]
Will wait with this till after the merge of #133. Currently, this enforces both correctness and usage of type annotations (ignoring external non-type libraries)

**Comment by swillner** [comment]
@znicholls Ok, I target the PR#133 branch now

**Comment by znicholls** [comment]
> usage of type annotations

This feels so wrong in Python, I'm not sure if I am ok with it. @rgieseke @lewisjared ?

**Comment by swillner** [comment]
>> enforces... usage of type annotations ...

Still it's just STATIC checking and only annotation, so making the code more robust. We can still use arbitrary duck typing using `Any` (see Mypy docs), though in most cases specifying the type requires almost no additional efforts.

**Comment by swillner** [comment]
https://stackoverflow.com/questions/42460289/why-to-use-types-in-python-3-5

**Comment by rgieseke** [comment]
Might increase barriers to contribute ... Could this be handled like code coverage? Something where 100% is nice, but might not always be possible?

**Comment by swillner** [comment]
Hmm, giving a share of "missed" lines would be difficult in this case. We could nevertheless be less strict here. On the other hand I believe that these will be used incrisingly in the future (they are a fairly recent feature), even by scientists, I hope ;)

**Comment by swillner** [comment]
We could have mypy in the makefile and encourage its use without enforcing it. Though, I'm afraid that would lead to many people just not caring about these things.

**Comment by swillner** [comment]
What about a compromise enforcing type annotations to be correct, but only if they are given and only warn about missing type annotations without enforcing their completeness?

**Comment by znicholls** [comment]
> What about a compromise enforcing type annotations to be correct, but only if they are given and only warn about missing type annotations without enforcing their completeness?

Sounds good to me.

**Comment by swillner** [comment]
Ok, adjusted ;)

**Comment by swillner** [comment]
@rgieseke @znicholls Ok, if I merge this now? It's going into the `timeseries-converter-advancement` branch anyway (#133).

**Comment by swillner** [comment]
Wil wait with merging for #133 and then merge this into master.

**Comment by rgieseke** [comment]
Sure, go ahead!

**Comment by znicholls** [comment]
> Wil wait with merging for #133 and then merge this into master.

Ok cool. One thing though, could we make it practice to never merge our own PRs? Just good practice I think from what I've seen in other projects.

**Comment by swillner** [comment]
@znicholls Merge this first, please

**Pull request merged**
